# ==========================================
# DefectFill 批量推理与生成全局配置文件
# ==========================================
paths:
  workspace_dir: "/home/doctor/tzh/MSD-Inpainting/data/CCM-Defect"
  model_config: "configs/train_config.yaml"  
  lora_weights: "/home/doctor/tzh/MSD-Inpainting/defectfill_lora_weights/checkpoint-epoch-10"
  train_dir: "/home/doctor/tzh/MSD-Inpainting/data/CCM-Defect/defect_train_concept"
  normal_dir: "/home/doctor/tzh/MSD-Inpainting/data/CCM-Defect/normal_components"
  output_dir: "/home/doctor/tzh/MSD-Inpainting/data/CCM-Defect/generated_defect_dataset_e10"
  stats_cache: "/home/doctor/tzh/MSD-Inpainting/data/CCM-Defect/defect_stats_cache.json"

inference:
  batch_size: 8                    # 【新增】每次从 DataLoader 抽取几张不同的正常图
  num_lfs_samples: 2               # 针对每张图，生成 8 个样本做 LFS (低保真度) 优选
  num_inference_steps: 30          
  guidance_scale: 7.5              
  negative_prompt: "blurry, smooth, unrealistic, artifacts" 
  base_seed: 42
  lpips_backbone: "alex"           # 可选: alex / vgg / squeeze

# 定义需要批量生成的任务清单
tasks:
  - defect: "<flexible_printed_circuit_crack>"
    comp: "<flexible_printed_circuit>"
    count: 20
  - defect: "<end_face_scratch>"
    comp: "<end_face>"
    count: 20
  - defect: "<lens_scratch>"
    comp: "<lens>"
    count: 20
  - defect: "<foreign_particle>"
    comp: "<end_face>"
    count: 20
  - defect: "<foreign_particle>"
    comp: "<lens>"
    count: 20
